#!/usr/bin/env bash
# notebook-session-push.sh — Build a session digest and push to NotebookLM.
#
# Per NotebookLM verdict (2026-05-16): daily auto-push dilutes signal —
# this is INVOKED MANUALLY at session boundaries, not by cron. The digest
# captures: live runtime_metrics, recent commits, journal anomalies, and
# any cicatrices touched in this session.
#
# Usage:
#   ./scripts/notebook-session-push.sh              # build + push, no query
#   ./scripts/notebook-session-push.sh --review     # also runs adversarial review query
#   ./scripts/notebook-session-push.sh --dry-run    # build digest, print path, don't push
set -euo pipefail

NOTEBOOK_ID="${APOLLO_NOTEBOOK_ID:-8344b94c-a014-4803-abea-076a55753cfd}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TS="$(date -u +%Y-%m-%dT%H%M%SZ)"
DATE_LOCAL="$(date +%Y-%m-%d)"
DIGEST_PATH="/tmp/apollo_session_digest_${TS}.md"

REVIEW=0
DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --review) REVIEW=1 ;;
    --dry-run) DRY_RUN=1 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

# Pull last metrics snapshot — fall back gracefully when daemon not running.
METRICS_BLOCK=$(sudo cat /var/lib/apollo/runtime_metrics.json 2>/dev/null | python3 -c "
import sys, json
try:
    m = json.load(sys.stdin)
    keys = ['cycles','failures','last_error','ais_score','ais_grade',
            'memory_pressure','p95_cycle_ms','stage_reason_avg_ms',
            'stage_reason_max_ms','thrashing_score','ioreport_p_cluster_pct',
            'smc_diagnostic','chromium_renderers_total',
            'chromium_renderers_frozen','current_workload']
    for k in keys:
        if k in m: print(f'- **{k}**: {m[k]}')
except Exception as e:
    print(f'- (runtime_metrics unavailable: {e})')
" 2>/dev/null || echo "- (runtime_metrics read failed)")

# Recent commits — last 15 across this session boundary.
COMMITS=$(cd "$REPO_ROOT" && git log --oneline -15)

# Journal anomaly summary — fails, errors, top reasons.
JOURNAL_BLOCK=$(sudo tail -500 /var/lib/apollo/journal.jsonl 2>/dev/null | python3 -c "
import sys, json
from collections import Counter
n = 0; fails = 0; errs = []; reasons = Counter()
for line in sys.stdin:
    try:
        d = json.loads(line); n += 1
        if d.get('success') is False: fails += 1
        if d.get('err'): errs.append(d['err'][:80])
        r = d.get('reason','')
        if r: reasons[r[:70]] += 1
    except Exception:
        pass
print(f'- **records scanned**: {n}')
print(f'- **success:false count**: {fails}')
print(f'- **distinct error strings**: {len(set(errs))}')
print(f'- **top reasons**:')
for r, c in reasons.most_common(6):
    print(f'  - {c:3} {r}')
for e in errs[:3]:
    print(f'  - err: {e}')
" 2>/dev/null || echo "- (journal read failed)")

# Capture daemon liveness — single source of truth.
LIVENESS=$(sudo launchctl print system/com.eduardocortez.systemoptimizerd 2>&1 \
  | grep -E "^\sstate|^\spid" | head -2 || echo "(launchctl not queryable)")

# Build the digest. Keep it under ~150 lines so it stays signal-dense per
# NotebookLM advice (avoid context dilution).
cat > "$DIGEST_PATH" <<EOF
# Apollo Optimizer — Session Digest ${DATE_LOCAL} (${TS})

## Hardware + Env (static)
- MacBook Air M1 8 GB RAM, macOS 26 Tahoe
- Daemon path: /usr/local/libexec/apollo-optimizerd
- launchd label: com.eduardocortez.systemoptimizerd

## Daemon liveness
\`\`\`
${LIVENESS}
\`\`\`

## Live runtime metrics
${METRICS_BLOCK}

## Recent commits (last 15)
\`\`\`
${COMMITS}
\`\`\`

## Journal anomalies (last 500 entries)
${JOURNAL_BLOCK}

## Session-bound notes
- Push generated by \`scripts/notebook-session-push.sh\` — not a cron job.
- Discard rule: this digest is signal-dense. If you find yourself pushing
  the same content twice in 24h, the second push is noise — skip it.
- If NotebookLM disagrees with a metric here, trust the metric (CLAUDE.md
  2026-05-07 lesson — NotebookLM is research aid, not gatekeeper).
EOF

echo "[digest] built ${DIGEST_PATH} ($(wc -l < "$DIGEST_PATH") lines)"

if [ "$DRY_RUN" = "1" ]; then
  echo "[digest] --dry-run: not pushing"
  exit 0
fi

# Push via nlm CLI.
if ! command -v nlm >/dev/null 2>&1; then
  echo "[digest] nlm CLI not found in PATH — install it or run mcp version manually." >&2
  exit 3
fi

TITLE="Session Digest ${DATE_LOCAL} ${TS}"
echo "[push] nlm source add → notebook ${NOTEBOOK_ID}"
nlm source add "$NOTEBOOK_ID" --file "$DIGEST_PATH" --title "$TITLE" --wait

if [ "$REVIEW" = "1" ]; then
  echo "[review] querying NotebookLM for severity-ranked gap-sweep…"
  nlm notebook query "$NOTEBOOK_ID" \
    "Just ingested '${TITLE}'. Severity-ranked gap-sweep vs prior digests: name any regression pattern this session re-introduced, any cicatriz not properly guarded, and any p95/AIS regression worth flagging. Be specific — cite commits. Do NOT inflate everything to Critical. If everything is green, say so plainly." || true
fi

echo "[done] $TITLE"
