//! Optimization Skills — persistent recipes learned from experience.
//!
//! Inspired by Hermes Agent's self-improving skills system.
//! When Apollo discovers a sequence of actions that reliably reduces pressure,
//! it saves it as a "skill" — a reusable recipe with measured success rate.
//!
//! Skills are persisted to disk and loaded on startup, surviving restarts.
//! Each skill has a trigger condition and a measured effectiveness.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;

/// Origin of an optimization skill: individually learned or batch-induced.
///
/// Seed type for future refactors — does not affect the current public interface.
/// Individual skills are learned from direct throttle-outcome observations.
/// Induced skills are generated by the rule inducer from co-occurrence patterns.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SkillOrigin {
    Individual,
    Induced,
}

impl SkillOrigin {
    /// Infer origin from skill name convention: "group:" and "batch:" prefixes
    /// indicate induced skills; anything else is individually learned.
    pub fn from_name(name: &str) -> Self {
        if name.starts_with("group:") || name.starts_with("batch:") {
            SkillOrigin::Induced
        } else {
            SkillOrigin::Individual
        }
    }
}

/// A learned optimization recipe.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OptimizationSkill {
    /// Human-readable name (e.g., "cloud_sync_throttle").
    pub name: String,
    /// Trigger: minimum pressure to activate.
    ///
    /// BUG-03 audit: callers cast f64 memory_pressure to f32 before comparison.
    /// The f64→f32 cast introduces ±2.4e-8 jitter (half an f32 ULP at 0.5–0.8).
    /// At threshold values in the 0.55–0.70 range, this is ~3×10⁻⁸ relative error —
    /// negligible compared to the ±0.01 pressure noise floor. Keeping f32 avoids a
    /// breaking change to the serialized `optimization_skills.json` schema.
    pub min_pressure: f32,
    /// Trigger: workload pattern (e.g., "Browser", "Build").
    pub workload_hint: String,
    /// Action: process names to throttle.
    pub throttle_targets: Vec<String>,
    /// Measured success rate [0, 1].
    pub success_rate: f32,
    /// Total times applied.
    pub apply_count: u32,
    /// Total times pressure dropped after applying.
    pub success_count: u32,
}

impl OptimizationSkill {
    /// Record an application result.
    pub fn record(&mut self, was_effective: bool) {
        self.apply_count += 1;
        if was_effective {
            self.success_count += 1;
        }
        self.success_rate = self.success_count as f32 / self.apply_count.max(1) as f32;
    }

    /// Is this skill reliable? (≥5 applications, ≥60% success rate)
    pub fn is_reliable(&self) -> bool {
        self.apply_count >= 5 && self.success_rate >= 0.60
    }

    /// Should this skill be retired?
    ///
    /// Two conditions:
    /// - **Primary** (≥10 obs, <35%): clearly ineffective — below noise floor.
    /// - **Zombie** (≥20 obs, <50%): consistently mediocre — never crosses the
    ///   reliable threshold (60%) and occupies a trial slot indefinitely.
    pub fn should_retire(&self) -> bool {
        (self.apply_count >= 10 && self.success_rate < 0.35)
            || (self.apply_count >= 20 && self.success_rate < 0.50)
    }

    /// EMA-update min_pressure toward the pressure where this skill
    /// was actually applied (α = 0.20).  Called after effective trials
    /// so the skill self-calibrates to its real operating range.
    pub fn adapt_pressure(&mut self, pressure: f32) {
        self.min_pressure = self.min_pressure * 0.80 + pressure * 0.20;
    }
}

/// Returns true if the process name looks like an Apple OS daemon or system
/// infrastructure process that should never become a skill target.
///
/// This is a structural heuristic on top of the explicit `protected_processes()`
/// list — it catches system processes we haven't explicitly listed yet, based on
/// macOS naming conventions:
/// - `com.apple.*`  — Apple reverse-domain services (XPC, agents, extensions)
/// - `*DriverKit*`  — DriverKit user-space drivers
/// - `org.pqrs.*`   — Karabiner / third-party kernel extensions
/// - `kernel_task`  — macOS kernel placeholder process
/// - `launchd`      — PID 1, never throttleable
fn is_system_process_name(name: &str) -> bool {
    name.starts_with("com.apple.")
        || name.starts_with("org.pqrs.")
        || name.contains("DriverKit")
        || name == "kernel_task"
        || name == "launchd"
}

/// Registry of learned optimization skills.
pub struct SkillRegistry {
    skills: HashMap<String, OptimizationSkill>,
}

impl Default for SkillRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl SkillRegistry {
    pub fn new() -> Self {
        Self {
            skills: HashMap::new(),
        }
    }

    /// Learn a new skill from observed effective throttle patterns.
    pub fn learn(&mut self, name: &str, pressure: f32, workload: &str, targets: Vec<String>) {
        // Filter protected OS daemons and system processes at ingestion time.
        // Two-layer check:
        // 1. Unified exact-match oracle (safety::is_protected_name) — covers
        //    Tier 1 OS essentials, Tier 2 infra services, Tier 3 dev runtimes.
        //    Replaces previous substring scan which over-protected (e.g.,
        //    "WindowServer-helper" matched "WindowServer" as false-positive).
        //    Saltzer & Kaashoek 2009 §3.3 Complete Mediation.
        // 2. Structural heuristic: Apple/system naming patterns that signal
        //    OS infrastructure — these should never be skill targets regardless
        //    of observed correlations.
        let clean_targets: Vec<String> = targets
            .into_iter()
            .filter(|t| !crate::engine::safety::is_protected_name(t) && !is_system_process_name(t))
            .collect();
        if clean_targets.is_empty() {
            return;
        }
        let skill = self
            .skills
            .entry(name.to_string())
            .or_insert_with(|| OptimizationSkill {
                name: name.to_string(),
                min_pressure: pressure,
                workload_hint: workload.to_string(),
                throttle_targets: clean_targets.clone(),
                success_rate: 0.5,
                apply_count: 0,
                success_count: 0,
            });
        // Update pressure threshold with EMA.
        skill.min_pressure = skill.min_pressure * 0.9 + pressure * 0.1;
    }

    /// Record result for a skill.
    pub fn record_result(&mut self, name: &str, was_effective: bool) {
        if let Some(skill) = self.skills.get_mut(name) {
            skill.record(was_effective);
        }
    }

    /// Record result and, on success, EMA-adapt the skill's pressure threshold
    /// toward the pressure at which it was applied.  Use this in the trial loop
    /// so skills converge to their real operating range over time.
    pub fn record_result_with_pressure(&mut self, name: &str, was_effective: bool, pressure: f32) {
        if let Some(skill) = self.skills.get_mut(name) {
            skill.record(was_effective);
            if was_effective {
                skill.adapt_pressure(pressure);
            }
        }
    }

    /// Get reliable skills matching current conditions.
    pub fn matching_skills(&self, pressure: f32, workload: &str) -> Vec<&OptimizationSkill> {
        self.skills
            .values()
            .filter(|s| {
                s.is_reliable()
                    && pressure >= s.min_pressure
                    && (s.workload_hint == workload || s.workload_hint == "any")
            })
            .collect()
    }

    /// Pick one unproven induced skill to trial this cycle.
    ///
    /// Induced skills (group:/batch:) start with apply_count=0 and can never
    /// reach is_reliable() without being applied first. This method returns
    /// the single highest-priority unproven skill at current pressure so it
    /// gets one real observation per call. Caller records the result via
    /// record_result() after measuring pressure delta.
    ///
    /// Criteria: apply_count < 10, pressure >= min_pressure, not retired,
    /// workload matches (skill.workload_hint == "any" OR == current workload).
    /// Priority: fewest applications first (round-robin exploration).
    pub fn next_trial_skill(&self, pressure: f32, workload: &str) -> Option<&OptimizationSkill> {
        self.skills
            .values()
            .filter(|s| {
                s.apply_count < 10
                    && !s.should_retire()
                    && pressure >= s.min_pressure
                    && (s.name.starts_with("group:") || s.name.starts_with("batch:"))
                    && (s.workload_hint == "any" || s.workload_hint == workload)
            })
            .min_by_key(|s| s.apply_count)
    }

    /// Remove induced skills whose ALL throttle targets are protected.
    /// These skills can never execute and would spin forever in the trial loop.
    /// `protected` is the combined hard + policy protected set.
    pub fn purge_unexecutable(&mut self, protected: &[&str]) {
        self.skills.retain(|name, skill| {
            if !name.starts_with("group:") && !name.starts_with("batch:") {
                return true; // keep individual skills unconditionally
            }
            // Keep if at least one target is NOT protected.
            skill.throttle_targets.iter().any(|target| {
                let tl = target.to_ascii_lowercase();
                !protected
                    .iter()
                    .any(|p| tl.contains(&p.to_ascii_lowercase()))
            })
        });
    }

    /// Register an autonomously induced skill (from rule_inducer).
    /// Skips if a skill with the same name already exists.
    /// Returns true if the skill was added.
    pub fn register_induced(&mut self, skill: OptimizationSkill) -> bool {
        if self.skills.contains_key(&skill.name) {
            return false;
        }
        self.skills.insert(skill.name.clone(), skill);
        true
    }

    /// Snapshot of all skill names (for duplicate checking in rule_inducer).
    pub fn name_set(&self) -> std::collections::HashSet<String> {
        self.skills.keys().cloned().collect()
    }

    /// Cross-feed: boost a skill's success_count when external Bayesian evidence
    /// (e.g., OutcomeTracker or CausalGraph) is stronger than trial data.
    ///
    /// Only applies if:
    ///   - The skill exists.
    ///   - `evidence_rate` exceeds the current `success_rate` by at least `min_gap`.
    ///   - The skill has ≥ `min_apply_count` applications (enough to be meaningful).
    ///
    /// Returns `true` if a boost was applied.
    pub fn cross_feed_boost(
        &mut self,
        name: &str,
        evidence_rate: f64,
        min_gap: f64,
        min_apply_count: u32,
    ) -> bool {
        if let Some(skill) = self.skills.get_mut(name) {
            if skill.apply_count >= min_apply_count
                && (evidence_rate - skill.success_rate as f64) >= min_gap
            {
                skill.success_count = skill.success_count.saturating_add(1);
                skill.apply_count = skill.apply_count.saturating_add(1);
                skill.success_rate = skill.success_count as f32 / skill.apply_count.max(1) as f32;
                return true;
            }
        }
        false
    }

    /// Query the success_rate for a skill by name. Returns `None` if not found.
    pub fn success_rate(&self, name: &str) -> Option<f32> {
        self.skills.get(name).map(|s| s.success_rate)
    }

    /// Query apply_count for a skill by name. Returns `None` if not found.
    pub fn apply_count(&self, name: &str) -> Option<u32> {
        self.skills.get(name).map(|s| s.apply_count)
    }

    /// Skill-Aware Prediction signal (Phase 3.1 — Sprint 6).
    ///
    /// Aggregates the historical success of reliable skills matching the given
    /// workload into a single [0, 1] signal. Used by `apply_specialist_voting`
    /// to modulate the confidence of non-Observe interventions: in workloads
    /// where past throttle-class actions have empirically worked, specialist
    /// votes are amplified; where they have failed, votes are damped.
    ///
    /// Weighting: each skill contributes `success_rate * apply_count`, so a
    /// skill with 100 applications dominates one with 5 — more evidence wins.
    /// Skills with `workload_hint == "any"` are included for every workload.
    ///
    /// Returns `None` when no reliable skill matches — caller should treat
    /// this as "no signal" and leave the vote weight at 1.0 (neutral).
    pub fn workload_success_signal(&self, workload: &str) -> Option<f32> {
        let mut weighted_sum = 0.0_f32;
        let mut weight_total = 0.0_f32;
        for s in self.skills.values() {
            if !s.is_reliable() {
                continue;
            }
            if s.workload_hint != "any" && s.workload_hint != workload {
                continue;
            }
            let w = s.apply_count as f32;
            weighted_sum += s.success_rate * w;
            weight_total += w;
        }
        if weight_total == 0.0 {
            None
        } else {
            Some((weighted_sum / weight_total).clamp(0.0, 1.0))
        }
    }

    /// Retire ineffective skills.
    pub fn gc(&mut self) {
        self.skills.retain(|_, s| !s.should_retire());
    }

    /// Number of skills.
    pub fn len(&self) -> usize {
        self.skills.len()
    }

    /// Number of reliable skills.
    pub fn reliable_count(&self) -> usize {
        self.skills.values().filter(|s| s.is_reliable()).count()
    }

    /// Snapshot all skills as a cloned map — used by LearnedState::collect().
    pub fn snapshot(&self) -> HashMap<String, OptimizationSkill> {
        self.skills.clone()
    }

    /// Restore skills from a persisted map — used by LearnedState::apply().
    /// Replaces the entire registry; existing skills are discarded.
    pub fn restore_from_map(&mut self, map: HashMap<String, OptimizationSkill>) {
        // Purge skills whose keys reference protected OS daemons or system
        // process naming patterns. Guards against stale disk state from before
        // these protections were added.
        // Migrated from substring scan over protected_processes() to the
        // unified is_protected_name() oracle (Tier 1/2/3) — closes
        // "WindowServer-helper" false-positive class. Saltzer & Kaashoek 2009
        // §3.3 Complete Mediation.
        self.skills = map
            .into_iter()
            .filter(|(k, _)| {
                // Strip skill prefix (throttle:/group:/induced:) to get process name
                let proc_name = k
                    .trim_start_matches("throttle:")
                    .trim_start_matches("group:")
                    .trim_start_matches("induced:");
                !crate::engine::safety::is_protected_name(proc_name)
                    && !is_system_process_name(proc_name)
            })
            .collect();
    }

    /// Persist to disk.
    pub fn persist(&self, path: &Path) {
        if let Ok(json) = serde_json::to_string(&self.skills) {
            let _ = std::fs::write(path, json);
        }
    }

    /// Load from disk.
    pub fn load(&mut self, path: &Path) {
        if let Ok(data) = std::fs::read_to_string(path) {
            if let Ok(skills) = serde_json::from_str::<HashMap<String, OptimizationSkill>>(&data) {
                self.skills = skills;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_skill_reliability() {
        let mut s = OptimizationSkill {
            name: "test".into(),
            min_pressure: 0.70,
            workload_hint: "any".into(),
            throttle_targets: vec!["Dropbox".into()],
            success_rate: 0.0,
            apply_count: 0,
            success_count: 0,
        };
        for _ in 0..8 {
            s.record(true);
        }
        for _ in 0..2 {
            s.record(false);
        }
        assert!(s.is_reliable()); // 80% success
        assert!(!s.should_retire());
    }

    #[test]
    fn test_skill_retirement() {
        let mut s = OptimizationSkill {
            name: "bad".into(),
            min_pressure: 0.50,
            workload_hint: "any".into(),
            throttle_targets: vec![],
            success_rate: 0.0,
            apply_count: 0,
            success_count: 0,
        };
        for _ in 0..10 {
            s.record(false);
        }
        assert!(s.should_retire());
    }

    #[test]
    fn test_registry_learn_and_match() {
        let mut reg = SkillRegistry::new();
        reg.learn("cloud_throttle", 0.70, "any", vec!["Dropbox".into()]);
        for _ in 0..10 {
            reg.record_result("cloud_throttle", true);
        }
        let matches = reg.matching_skills(0.75, "any");
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].name, "cloud_throttle");
    }

    #[test]
    fn test_registry_gc() {
        let mut reg = SkillRegistry::new();
        reg.learn("bad_skill", 0.50, "any", vec![]);
        for _ in 0..15 {
            reg.record_result("bad_skill", false);
        }
        reg.gc();
        assert_eq!(reg.len(), 0);
    }

    #[test]
    fn test_zombie_retirement_secondary_condition() {
        // Zombie: 20 obs but only 40% success (0.35–0.49 band, never reliable).
        let mut s = OptimizationSkill {
            name: "zombie".into(),
            min_pressure: 0.50,
            workload_hint: "any".into(),
            throttle_targets: vec![],
            success_rate: 0.0,
            apply_count: 0,
            success_count: 0,
        };
        for i in 0..20 {
            s.record(i % 5 < 2); // 2/5 = 40% success
        }
        assert!(s.apply_count >= 20);
        assert!(s.success_rate < 0.50);
        assert!(
            s.should_retire(),
            "zombie skill at 40% after 20 obs should retire"
        );
    }

    #[test]
    fn test_zombie_retirement_does_not_over_retire() {
        // 18 obs at 48% — below 50% but not yet at 20 obs threshold → keep alive.
        let mut s = OptimizationSkill {
            name: "marginal".into(),
            min_pressure: 0.50,
            workload_hint: "any".into(),
            throttle_targets: vec![],
            success_rate: 0.0,
            apply_count: 0,
            success_count: 0,
        };
        for i in 0..18 {
            s.record(i % 2 == 0); // alternating 50% — stays near 0.50
        }
        // 9 successes / 18 = 0.50 exactly — should NOT retire on secondary
        // (secondary: < 0.50, not <= 0.50)
        assert!(!s.should_retire(), "50% at 18 obs should not retire yet");
    }

    #[test]
    fn test_adapt_pressure_ema() {
        let mut s = OptimizationSkill {
            name: "adapt".into(),
            min_pressure: 0.60,
            workload_hint: "any".into(),
            throttle_targets: vec![],
            success_rate: 0.0,
            apply_count: 0,
            success_count: 0,
        };
        // EMA toward 0.75: 0.60 * 0.80 + 0.75 * 0.20 = 0.48 + 0.15 = 0.63
        s.adapt_pressure(0.75);
        assert!((s.min_pressure - 0.63).abs() < 0.001);
    }

    #[test]
    fn test_record_result_with_pressure_adapts_on_success() {
        let mut reg = SkillRegistry::new();
        reg.learn("adapt_skill", 0.60, "any", vec!["App".into()]);
        let before = reg.skills["adapt_skill"].min_pressure;
        reg.record_result_with_pressure("adapt_skill", true, 0.75);
        let after = reg.skills["adapt_skill"].min_pressure;
        // Should have shifted toward 0.75
        assert!(
            after > before,
            "effective trial at higher pressure should shift threshold up"
        );
        assert!((after - (before * 0.80 + 0.75 * 0.20)).abs() < 0.002);
    }

    #[test]
    fn test_record_result_with_pressure_no_adapt_on_failure() {
        let mut reg = SkillRegistry::new();
        reg.learn("no_adapt", 0.60, "any", vec!["App".into()]);
        let before = reg.skills["no_adapt"].min_pressure;
        reg.record_result_with_pressure("no_adapt", false, 0.90);
        let after = reg.skills["no_adapt"].min_pressure;
        // Failure should not shift threshold
        assert_eq!(
            after, before,
            "failed trial should not adapt pressure threshold"
        );
    }

    // ── next_trial_skill() tests ──────────────────────────────────────────────

    fn induced_skill(name: &str, min_pressure: f32, apply_count: u32) -> OptimizationSkill {
        OptimizationSkill {
            name: name.to_string(),
            min_pressure,
            workload_hint: "any".to_string(),
            throttle_targets: vec!["SomeApp".to_string()],
            success_rate: 0.5,
            apply_count,
            success_count: apply_count / 2,
        }
    }

    #[test]
    fn test_next_trial_skill_empty_registry() {
        let reg = SkillRegistry::new();
        assert!(reg.next_trial_skill(0.80, "any").is_none());
    }

    #[test]
    fn test_next_trial_skill_returns_unproven_induced() {
        let mut reg = SkillRegistry::new();
        reg.register_induced(induced_skill("group:safari+dropbox", 0.60, 0));
        let trial = reg.next_trial_skill(0.70, "any");
        assert!(trial.is_some());
        assert_eq!(trial.unwrap().name, "group:safari+dropbox");
    }

    #[test]
    fn test_next_trial_skill_skips_non_induced() {
        let mut reg = SkillRegistry::new();
        reg.learn("cloud_throttle", 0.60, "any", vec!["Dropbox".into()]);
        assert!(reg.next_trial_skill(0.80, "any").is_none());
    }

    #[test]
    fn test_next_trial_skill_pressure_gate() {
        let mut reg = SkillRegistry::new();
        reg.register_induced(induced_skill("group:heavy", 0.65, 0));
        assert!(reg.next_trial_skill(0.64, "any").is_none());
        assert!(reg.next_trial_skill(0.65, "any").is_some());
    }

    #[test]
    fn test_next_trial_skill_cap_at_ten() {
        let mut reg = SkillRegistry::new();
        reg.register_induced(induced_skill("group:worn", 0.50, 10));
        assert!(reg.next_trial_skill(0.80, "any").is_none());
        reg.register_induced(induced_skill("group:fresh", 0.50, 9));
        assert!(reg.next_trial_skill(0.80, "any").is_some());
    }

    #[test]
    fn test_next_trial_skill_prefers_fewest_applications() {
        let mut reg = SkillRegistry::new();
        reg.register_induced(induced_skill("group:more_used", 0.50, 5));
        reg.register_induced(induced_skill("batch:less_used", 0.50, 2));
        let trial = reg.next_trial_skill(0.80, "any");
        assert_eq!(trial.unwrap().name, "batch:less_used");
    }

    #[test]
    fn test_next_trial_skill_skips_retiring() {
        let mut reg = SkillRegistry::new();
        let mut s = induced_skill("group:bad", 0.50, 10);
        s.success_rate = 0.0;
        s.success_count = 0;
        reg.register_induced(s);
        assert!(reg.next_trial_skill(0.80, "any").is_none());
    }

    #[test]
    fn test_next_trial_skill_workload_filter() {
        let mut reg = SkillRegistry::new();
        // batch skill tagged "browsing" — should appear when workload matches
        let mut browser_skill = induced_skill("batch:tab+sync", 0.50, 0);
        browser_skill.workload_hint = "browsing".to_string();
        reg.register_induced(browser_skill);
        // group skill "any" — always available
        reg.register_induced(induced_skill("group:daemon+helper", 0.50, 0));

        // "build" workload: only "any" skill visible
        let build_trial = reg.next_trial_skill(0.70, "build");
        assert!(build_trial.is_some());
        assert_eq!(build_trial.unwrap().name, "group:daemon+helper");

        // "browsing" workload: both visible, "any" and "browsing" skill eligible
        let mut count = 0;
        let mut registry2 = SkillRegistry::new();
        let mut b1 = induced_skill("batch:tab+sync", 0.50, 0);
        b1.workload_hint = "browsing".to_string();
        registry2.register_induced(b1);
        // next_trial_skill returns one at a time; drain all eligible
        while registry2.next_trial_skill(0.70, "browsing").is_some() {
            let name = registry2
                .next_trial_skill(0.70, "browsing")
                .unwrap()
                .name
                .clone();
            registry2.record_result(&name, false);
            count += 1;
            if count > 20 {
                break;
            }
        }
        assert!(
            count >= 1,
            "browsing skill should be trialed during browsing workload"
        );
    }

    // ── purge_unexecutable() tests ────────────────────────────────────────────

    #[test]
    fn test_purge_unexecutable_empty_registry() {
        let mut reg = SkillRegistry::new();
        reg.purge_unexecutable(&["kernel_task"]);
        assert_eq!(reg.len(), 0);
    }

    #[test]
    fn test_purge_unexecutable_removes_all_protected_targets() {
        let mut reg = SkillRegistry::new();
        let mut skill = induced_skill("group:protected_only", 0.50, 0);
        skill.throttle_targets = vec!["kernel_task".into(), "WindowServer".into()];
        reg.register_induced(skill);
        reg.purge_unexecutable(&["kernel_task", "windowserver"]);
        assert_eq!(reg.len(), 0, "all targets protected → skill removed");
    }

    #[test]
    fn test_purge_unexecutable_keeps_skill_with_free_target() {
        let mut reg = SkillRegistry::new();
        let mut skill = induced_skill("group:mixed", 0.50, 0);
        skill.throttle_targets = vec!["kernel_task".into(), "Brave Browser".into()];
        reg.register_induced(skill);
        // "brave browser" is not in protected list → skill kept
        reg.purge_unexecutable(&["kernel_task"]);
        assert_eq!(reg.len(), 1, "skill with at least one free target kept");
    }

    #[test]
    fn test_purge_unexecutable_case_insensitive() {
        let mut reg = SkillRegistry::new();
        let mut skill = induced_skill("group:case_test", 0.50, 0);
        skill.throttle_targets = vec!["CoreAudiod".into()];
        reg.register_induced(skill);
        // lowercase in protected list should still match "CoreAudiod"
        reg.purge_unexecutable(&["coreaudiod"]);
        assert_eq!(reg.len(), 0, "case-insensitive substring match should work");
    }

    #[test]
    fn test_purge_unexecutable_preserves_individual_skills() {
        let mut reg = SkillRegistry::new();
        // Individual (non-induced) skills are never removed.
        // Use a non-protected target so learn() doesn't silently drop the skill.
        reg.learn("cloud_throttle", 0.50, "any", vec!["Dropbox".into()]);
        reg.purge_unexecutable(&["Dropbox"]);
        assert_eq!(reg.len(), 1, "individual skills always kept");
    }

    #[test]
    fn test_purge_unexecutable_empty_protected_list() {
        let mut reg = SkillRegistry::new();
        reg.register_induced(induced_skill("group:any_target", 0.50, 0));
        reg.purge_unexecutable(&[]);
        assert_eq!(reg.len(), 1, "empty protected list → all skills kept");
    }

    // ── Loop 1: skill outcome observation tests ─────────────────────────────

    #[test]
    fn test_skill_observes_outcome_via_throttle_prefix() {
        let mut reg = SkillRegistry::new();
        reg.learn("throttle:Dropbox", 0.70, "any", vec!["Dropbox".into()]);
        assert_eq!(reg.skills["throttle:Dropbox"].apply_count, 0);
        // Simulate resolved outcome feeding back to skill
        reg.record_result_with_pressure("throttle:Dropbox", true, 0.72);
        assert_eq!(reg.skills["throttle:Dropbox"].apply_count, 1);
        assert_eq!(reg.skills["throttle:Dropbox"].success_count, 1);
    }

    #[test]
    fn test_skill_adapts_pressure_from_outcome() {
        let mut reg = SkillRegistry::new();
        reg.learn("throttle:Safari", 0.65, "any", vec!["Safari".into()]);
        let before = reg.skills["throttle:Safari"].min_pressure;
        // Effective outcome at higher pressure → skill adapts upward
        reg.record_result_with_pressure("throttle:Safari", true, 0.80);
        let after = reg.skills["throttle:Safari"].min_pressure;
        assert!(
            after > before,
            "effective outcome at higher pressure should shift threshold up"
        );
    }

    // ── Phase 3.1 — Skill-Aware Prediction signal ────────────────────────────

    fn make_reliable_skill(
        name: &str,
        workload: &str,
        success_rate: f32,
        apply_count: u32,
    ) -> OptimizationSkill {
        let success_count = (success_rate * apply_count as f32).round() as u32;
        OptimizationSkill {
            name: name.into(),
            min_pressure: 0.60,
            workload_hint: workload.into(),
            throttle_targets: vec!["target".into()],
            success_rate,
            apply_count,
            success_count,
        }
    }

    #[test]
    fn workload_success_signal_returns_none_when_empty() {
        let reg = SkillRegistry::new();
        assert_eq!(reg.workload_success_signal("coding"), None);
    }

    #[test]
    fn workload_success_signal_excludes_unreliable_skills() {
        let mut reg = SkillRegistry::new();
        // Below reliability bar: apply_count < 5
        reg.skills.insert(
            "fresh".into(),
            make_reliable_skill("fresh", "coding", 0.90, 3),
        );
        assert_eq!(reg.workload_success_signal("coding"), None);
    }

    #[test]
    fn workload_success_signal_excludes_non_matching_workload() {
        let mut reg = SkillRegistry::new();
        reg.skills.insert(
            "browser_only".into(),
            make_reliable_skill("browser_only", "browser", 0.90, 20),
        );
        assert_eq!(reg.workload_success_signal("coding"), None);
        assert!(reg.workload_success_signal("browser").is_some());
    }

    #[test]
    fn workload_success_signal_includes_any_workload() {
        let mut reg = SkillRegistry::new();
        reg.skills.insert(
            "universal".into(),
            make_reliable_skill("universal", "any", 0.80, 10),
        );
        let sig = reg.workload_success_signal("coding").unwrap();
        assert!((sig - 0.80).abs() < 0.001);
    }

    #[test]
    fn workload_success_signal_weights_by_apply_count() {
        let mut reg = SkillRegistry::new();
        // 100 applications at 90% — dominant
        reg.skills.insert(
            "heavy".into(),
            make_reliable_skill("heavy", "coding", 0.90, 100),
        );
        // 5 applications at 60% — minimal weight
        reg.skills.insert(
            "light".into(),
            make_reliable_skill("light", "coding", 0.60, 5),
        );
        let sig = reg.workload_success_signal("coding").unwrap();
        // Weighted avg = (0.90*100 + 0.60*5) / 105 = 93/105 ≈ 0.8857
        assert!(
            (sig - 0.8857).abs() < 0.001,
            "weighted average failed, got {sig}"
        );
    }

    #[test]
    fn test_induced_skill_gets_outcome_feedback() {
        let mut reg = SkillRegistry::new();
        reg.register_induced(induced_skill("group:safari+dropbox", 0.60, 0));
        // Simulate trial outcome feedback
        reg.record_result_with_pressure("group:safari+dropbox", true, 0.70);
        assert_eq!(reg.skills["group:safari+dropbox"].apply_count, 1);
        assert_eq!(reg.skills["group:safari+dropbox"].success_count, 1);
        // Pressure should have adapted
        let p = reg.skills["group:safari+dropbox"].min_pressure;
        assert!(p > 0.60, "pressure should adapt toward 0.70, got {p}");
    }
}
